[[at_spi2_atk]]
arch = "armv7l"
git-tree-sha1 = "73e07ca253713f81e3f595a36075299918abd7de"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "c37eb18b153c8b7f3a8c7468e29457a692d64b68b2c170d0aba1fe4fdb6fadea"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.armv7l-linux-gnueabihf.tar.gz"
[[at_spi2_atk]]
arch = "i686"
git-tree-sha1 = "e868e0fd1c4c8ab06188f4be2f9dff7989cd0e8e"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "ec5dcbd907039ed22f5b0b05d10415340ae6ea1d3e3d01de3ee24a3ff7eef238"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.i686-linux-musl.tar.gz"
[[at_spi2_atk]]
arch = "aarch64"
git-tree-sha1 = "d44a0260e807143c5d3c13b9122aab7d14aeafe4"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "711a7baae397a9563532d68043b6e7d20c61a2b51f7e6ae203f86eb69a20865a"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.aarch64-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "armv7l"
git-tree-sha1 = "cbe55d2db408ee8b33eab90270ad7a93ebabee65"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "ccb4b40dd16f9318db32d612d4d16bf6669074aad1ecf52660dcce627305585f"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.armv7l-linux-musleabihf.tar.gz"
[[at_spi2_atk]]
arch = "aarch64"
git-tree-sha1 = "18a18b344c250f315c21c44689d95004397f6baf"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "397854f7986e45f7b0af0a2e37cd2dc09f868b460c34417b605a6db3653e6042"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.aarch64-linux-musl.tar.gz"
[[at_spi2_atk]]
arch = "x86_64"
git-tree-sha1 = "b8cab9ed0d6c642d2606db0e98e64024d21bbcd6"
os = "freebsd"

    [[at_spi2_atk.download]]
    sha256 = "87b302c99fc6336b0672e6a60afdc23e41e8dfb9f0d646bbeebb282a0f2d989b"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.x86_64-unknown-freebsd11.1.tar.gz"
[[at_spi2_atk]]
arch = "i686"
git-tree-sha1 = "5327408a397212386cb130f834d9af0e80fe43ab"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "523f311b6d8ed1eef39cc2eeee1d7a736710b7866b53c5a3b7a04ea6f6fba321"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.i686-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "x86_64"
git-tree-sha1 = "2ab86133dc8186d6532ea3ac0d816b0349160458"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "13a738af2eb36ae14c92987e9dbac34292f02d0da298b95a2f431e908bfd38da"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.x86_64-linux-musl.tar.gz"
[[at_spi2_atk]]
arch = "x86_64"
git-tree-sha1 = "62dbbd7fd1c3188bda9fc14daff9dc72cfe65e14"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "7751e57d5b2ea991109ad568df2474de9a627def6c124d6e15f3b87cd52e85d1"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.x86_64-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "powerpc64le"
git-tree-sha1 = "1ae66a083366c79d92ec3daf061c4d112871ae7e"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "477b953fa5b5fba5365459012b165a630a86ad9ef0e530231d1ca07e1312cb7b"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+1/at_spi2_atk.v2.34.1.powerpc64le-linux-gnu.tar.gz"
