[[at_spi2_atk]]
arch = "aarch64"
git-tree-sha1 = "12ebfef9c571f88d73889dd89b09eea7265b9f46"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "f019d0ef3dbae9efea02ca0984cdc90fc4b2f338e8fd5a46936f447f828ed25f"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.aarch64-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "aarch64"
git-tree-sha1 = "d81e130f2a7c1e91b0fbe11bab09fd5afec12c91"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "6f48a0b4d26e9f65e679d8978f2d4e34c9f5b87c5aabe7f17b8ac20fad5005ac"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.aarch64-linux-musl.tar.gz"
[[at_spi2_atk]]
arch = "armv7l"
git-tree-sha1 = "08696fe5a1dda9d19018eb1db4a37e29be1e9c58"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "201258762a2184c67590c2875ae34f5ccf86a35d26c7feed317fdd5119132179"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.armv7l-linux-gnueabihf.tar.gz"
[[at_spi2_atk]]
arch = "armv7l"
git-tree-sha1 = "ee957db1324a5960876f3412883a71839a60a30b"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "4729819d9243ad0d7b3e8642eadc2f41b74c9e0b04c24597f3b3047001700026"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.armv7l-linux-musleabihf.tar.gz"
[[at_spi2_atk]]
arch = "i686"
git-tree-sha1 = "b62fd0b4eb762b57604435d85586c9171c7ebd0a"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "bcdd22c67a56f50b4a563a444a84d738dc4b496f5c34c72de00673a2bbb946e0"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.i686-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "i686"
git-tree-sha1 = "98801a7a2656e5dcbde6d44d1dbc24cebc24c68f"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "b421b34f76655e450a1b108de528cbdff20cbbcdfad2ed9677b8fc01f42e2f76"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.i686-linux-musl.tar.gz"
[[at_spi2_atk]]
arch = "powerpc64le"
git-tree-sha1 = "2cced6912a95aa7cdd1de9d68a2008640171478c"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "9072cad0f7316e7a96c7f177df988fd4a39f0a64f4c2b3a6826da0afa3e74ea6"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.powerpc64le-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "x86_64"
git-tree-sha1 = "2706890b5f8ec3aaa177096b36cef1476505a790"
libc = "glibc"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "f5481db56a03c52592ef6484bfbe33324aac22a59ba58fdfde8d9564c0f6ff2e"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.x86_64-linux-gnu.tar.gz"
[[at_spi2_atk]]
arch = "x86_64"
git-tree-sha1 = "a20c7ca4f2b5eacf7dd90b3757df0ef24279fa8c"
libc = "musl"
os = "linux"

    [[at_spi2_atk.download]]
    sha256 = "818bc784aa9f0ea38f8381e3cce74c1bad1c358e8683dfee8f9ee8d4e11c9021"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.x86_64-linux-musl.tar.gz"
[[at_spi2_atk]]
arch = "x86_64"
git-tree-sha1 = "09688b2ea1f31145e454d7023c19e079cfe93044"
os = "freebsd"

    [[at_spi2_atk.download]]
    sha256 = "a51d2c4849cb1cf8a2c03b79cb751115d2623be28c2a1083e6a2404194e2665f"
    url = "https://github.com/JuliaBinaryWrappers/at_spi2_atk_jll.jl/releases/download/at_spi2_atk-v2.34.1+2/at_spi2_atk.v2.34.1.x86_64-unknown-freebsd11.1.tar.gz"
